### ISSUE TITLE
Release `hex.pm` package 0.0.2

### ISSUE THREAD

**Issue by mmmries** [batate/elixir-pipes#9]
I was about to open a pull request to update the required version of Elixir to 1.0, but I noticed you already merged a pull request for this.

Can you publish a `0.0.2` version of the hex package so I can use it as a dependency in my library and still provide support for Elixir 1.0?

**Comment by batate** [comment]
Sorry about that!

You should be good now.

-bt

On Thu, May 28, 2015 at 11:42 PM, Michael <notifications@github.com> wrote:

> I was about to open a pull request to update the required version of
> Elixir to 1.0, but I noticed you already merged a pull request for this.
>
> Can you publish a 0.0.2 version of the hex package so I can use it as a
> dependency in my library and still provide support for Elixir 1.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/batate/elixir-pipes/issues/9>.
>



-- 

*Bruce Tate*  |  *CTO*  |  *512.772.4312*

*i**can**make**it**better**.com* <http://icanmakeitbetter.com>

*Innovation + Research. Made Simple*

**Comment by mmmries** [comment]
Thanks! :heart: :heart_eyes: :two_hearts: :tada: :balloon:
